### ISSUE TITLE
Builtin colors file not read

### ISSUE THREAD

**Issue by BigNoid** [phil65/KodiDevKit#4]
Not sure how to fix properly, but color aliases from [colors.xml](https://github.com/xbmc/xbmc/blob/master/system/colors.xml) and not in colors/defaults.xml give an error for invalid value in the colordiffuse attribute.

**Comment by phil65** [comment]
oh, right. will take a look.

**Comment by phil65** [comment]
this one should do the trick:
https://github.com/phil65/KodiDevKit/commit/b2454e45db795548d6b1feb9f07b69978b7cbe8e

**Comment by BigNoid** [comment]
Great, thx!
